#+title: Secrets

Secrets are managed with age encryption and integrated with nix using the wonderful [[https://github.com/ryantm/agenix?tab=readme-ov-file#ageidentitypaths][Agenix]] by ryantm.

* Editing Secrets

The list of secrets that can be created/edited is in [[file:secrets.nix]] and are populated with the following command.

#+begin_src shell
EDITOR=vim nix run github:ryantm/agenix -- -e cloudflare-api-env.age
#+end_src

If you change ssh keys and need to re-encrypt your age secrets the following command will re-encrypt all of them.

#+begin_src shell
EDITOR=vim nix run github:ryantm/agenix -- -r
#+end_src

* Authelia secrets

The majority of Authelia secrets are just 64 character long random strings that can be easily generated.

#+begin_src shell
nix run 'nixpkgs#authelia' -- crypto rand --length 64 --charset alphanumeric
#+end_src

a notable exception is =authelia-oicd-issuer.pem= which is actually an RSA keypair.

#+begin_src shell
nix run 'nixpkgs#authelia' -- crypto pair rsa generate
#+end_src

Apparently Authelia does support DSA keys which could be interesting in future.

** OIDC secrets

Most often we want to create OIDC keys, consisting of an encrypted secret
(supplied to the application) and a hash (given to Authelia). We can get both at
once with:

#+begin_src shell
nix run 'nixpkgs#authelia' -- crypto hash generate argon2 --random --random.length 72 --random.charset rfc3986
#+end_src

The secret itself should be put in =<service>-oidc-secret.age=, and the hash in =<service>-oidc-secret.txt=.

In order to work with [[file:~/Documents/Projects/golgi/modules/auth/clients.nix][clients.nix]] nicely, it is important that =<service>= be the
lowercase name of the "app" from [[file:~/Documents/Projects/golgi/site.nix][site.nix]], with dashes instead of spaces (e.g.
=home-assistant= instead of =Home Assistant=).

* Cloudflare

Any secret that ends in =env= such as =cloudflare-api-env.age= is actually an environment file not a raw secret.

#+begin_example
CLOUDFLARE_AUTH_TOKEN=<super secret token>
#+end_example
